version: '3.8'
networks:
  app: null
services:
  app:
    build: .
    volumes:
      - .:/var/www/app
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - app
    depends_on:
      - app

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    networks:
      - app
